### ISSUE TITLE
precondition checking

### ISSUE THREAD

**Issue by salehjg** [spcl/gemm_hls#11]
I was skimming through the codes and noticed that in `test/TestSimulation.cpp` we have this :
```
if (size_k % kMemoryWidthK != 0) {
    std::cerr << "K must be divisable by memory width." << std::endl;
    return 1;
  }
```
But the kernel reads data from respective input tensors with `MM_TRANSPOSE_WIDTH` as the burst length.
I might be missing something obvious but it seems like there might be a possibility for `kMemoryWidthK` to be less than `MM_TRANSPOSE_WIDTH`, in which case `test/TestSimulation.cpp` should be updated to this:
```
if (size_k % MM_TRANSPOSE_WIDTH != 0) {
...
  }
```

Again, I might be wrong.
btw, fantastic design, learned a lot from it.

**Comment by definelicht** [comment]
Hi there :-) The check right now is the most general, since there's an option to assume that `A` is already transposed, in which case the transpose width is not used.
But you are right that we should check for this when this option is set!
