### ISSUE TITLE
"Failed to initialize device memory."

### ISSUE THREAD

**Issue by fedefavaro** [spcl/gemm_hls#15]
Hi, I've successfully built and run the design in an Alveo U50 board up to certain matrix sizes. But when I increase the problem size I'm getting the following error:

```shell
$ ./RunHardware.exe 8192 4096 8192 hw off

[XRT] ERROR: std::bad_alloc
Execution failed with error: "Failed to initialize device memory.".
```

For smaller sizes, for example `4096 2048 4096` it works fine.

All sources and configuration are the original except for the MM_PART_NAME and MM_DSA_NAME which were modified to match the board. This is the `cmake` command I've used:
```shell
cmake ../ -DMM_DATA_TYPE=float -DMM_PARALLELISM_N=32 -DMM_PARALLELISM_M=8 -DMM_MEMORY_TILE_SIZE_N=512 -DMM_MEMORY_TILE_SIZE_M=512
```

What may be causing this issue?

**Comment by definelicht** [comment]
Hi Federico. My first intuition would be integer overflow somewhere, so it's allocated a negative number of bytes, which translates into a very large number in unsigned arithmetic. I have previously tested with 8192x8192 matrices, but I recently made some changes to the code passing the sizes at runtime.

I will see if I can reproduce this on one of our U250s.

**Comment by definelicht** [comment]
These sizes run successfully on our U250, so my initial hunch was wrong. The other explanation would be that you're allocating more than what fits in off-chip memory, but the U50 is supposed to have 8 GB of HBM.

Could it have something to do with the 32 virtual channels of the HBM interface? For example, if this would split the 8 GB of memory, there would be 256 MB per channel. This is enough for 4096x4096, but not for 8192x8192.

@fedefavaro I don't have access to the U50, so perhaps you can do the following experiment:
Make a trivial code (not using this repository or hlslib) that allocates a 8192x8192, 8192x4096, and 4096x4096 matrix on the device, and see if you get the same error?

**Comment by fedefavaro** [comment]
I believe you're right. I've done the experiments and the sizes 8192x8192, 8192x4096 failed with error:
```shell
[XRT] ERROR: std::bad_alloc
../src/host.cpp:124 Error calling cl::Buffer buffer_output(context, CL_MEM_USE_HOST_PTR | CL_MEM_WRITE_ONLY, matrix_size_bytes, source_hw_results.data(), &err), error code is: -6
```
The error code corresponds to: `CL_OUT_OF_HOST_MEMORY`.

The test with size 4096x4096 works fine.

**Comment by definelicht** [comment]
Thanks! I suppose they really implemented HBM as 32 different interfaces with 256 MB each.
This seems really impractical; I would've thought that they virtualize this. Unfortunately it would require some pretty substantial changes in the code to automatically split the matrices between different interfaces.

You could look into whether there's a way to expose more capacity on a single interface in Vitis?

**Comment by fedefavaro** [comment]
I want to believe there is an easy way to do it, or that they are working on it. I will look into it.

Thank you for your assistance!

**Comment by definelicht** [comment]
Cool, do you mind reporting back what you find out? I'm also interested. If it's a relatively easy fix it would be good to integrate it into the repo.

**Comment by fedefavaro** [comment]
I think I've found the answer: https://forums.xilinx.com/t5/Alveo-Accelerator-Cards/How-to-configure-data-layout-across-multiple-HBM-channels/m-p/1100342

> At this time, XRT is unable to allocate a buffer larger than 256MB when using the HBM. This is because the system treats the HBM like non-contiguous memory spaces. The hardware would allow for larger buffers, and this feature is coming in a future XRT update. 
However, at this time, you must break up your array into smaller blocks. The AXI switch in front of the HBM is physically wired to allow any master port to access any of the pseudo channels data. You could potentially write your RTL kernel to take advantage of this. 
_My question is: can we bind one array to multiple channels? If so, what is the default data layout across multiple channels? Can we configure it?_
Right now the answer is no, not directly.

It seems there is no easy way around it, so the best option is to wait for the XRT update.

In the meantime, it shouldn't be pretty simple to use one HBM bank per buffer, but that only allows some increase in the matrix sizes. So, it may not be worth adding it to the repo.

**Comment by fedefavaro** [comment]
I'd like to implement the discussed modification (using one HBM bank per buffer). Can you point me to where in the code should I look to make this changes? I'm familiar with the `<config_files>.ini` passed to the v++ linker in the vitis flow, but I'm not finding them in your code.

Also, from the host side I need to use the `cl_mem_ext_ptr_t` type. Is this supported in hlslib?

**Comment by definelicht** [comment]
Actually I haven't made the change to these config files yet, since the (in my opinion more convenient) command line parameters are still supported.

The code actually already supports using two banks with the `MM_TWO_DIMMS` parameter. You can see how it's implemented here: https://github.com/spcl/gemm_hls/blob/master/CMakeLists.txt#L193

You also need to perform the memory copies to the corresponding banks, which is done here: https://github.com/spcl/gemm_hls/blob/master/host/RunHardware.cpp#L133

I think it should be quite straightforward for you to extend this to 3 banks if you wish. Going to more would mean splitting up the matrices, which will start getting very hairy, so I wouldn't recommend that.
