### ISSUE TITLE
Floating point exception when running the design for uint8_t

### ISSUE THREAD

**Issue by kmhatre14** [spcl/gemm_hls#17]
Hello, 

Thanks for the awesome repo. That's a very well written code. :+1: 
I have synthesized the design for uint8_t, it synthesized correctly but gave me a `floating point exception (core dump)` when running the application. This is probably due to the division operation during verification where (diff / refVal). For uint8_t the refVal can become 0 and thus can give exception while running. It does make sense to have such division for float but it crashes when running it for uint8_t. 

For uint8_t we can just have a check if diff > 0, in that case, a true will be a mismatch. 

Thanks
kaustubh

**Comment by definelicht** [comment]
Thanks for reporting this! When using integer values, we can compare exact values anyway, so I will get rid of this division.
