### ISSUE TITLE
CMake for Vivado_HLS

### ISSUE THREAD

**Issue by prachikashikar** [spcl/gemm_hls#19]
Can anyone please help me in solving the following issue..

CMake Warning at hlslib/cmake/FindVitis.cmake:106 (message):
  vitis_hls used from Vitis 2020.1 and onwards introduces breaking changes to
  hls::stream.  Please pass -D__VITIS_HLS__ or -D__VIVADO_HLS__ in your
  synthesis script depending on which tool you are using to always use a
  working version.
Call Stack (most recent call first):
  CMakeLists.txt:78 (find_package)

CMake Error at /home/prachi/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Vitis (missing: Vitis_COMPILER Vitis_HLS Vitis_INCLUDE_DIRS
  Vitis_LIBRARIES Vitis_FLOATING_POINT_LIBRARY Vitis_VERSION
  Vitis_MAJOR_VERSION Vitis_MINOR_VERSION Vitis_PLATFORMINFO)
Call Stack (most recent call first):
  /home/prachi/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  hlslib/cmake/FindVitis.cmake:277 (find_package_handle_standard_args)
  CMakeLists.txt:78 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/prachi/gemm_hls/build/CMakeFiles/CMakeOutput.log".

**Comment by definelicht** [comment]
Hi @prachikashikar, did you make sure that Vitis is on your `PATH`? What does `which v++` return?

You can also point CMake directly to your Vitis installation directly, with `-DVITIS_ROOT=/opt/Xilinx/Vitis/2020.2` (replace `/opt/Xilinx/Vitis/2020.2` with the correct path on your system).

**Comment by prachikashikar** [comment]
Hi @definelicht , thank you for your reply.  
I also want to know how can I do this with vivado HLS than Vitis. I would be very grateful for your help.

**Comment by definelicht** [comment]
Xilinx have changed the flow to use `vitis_hls` now, so it looks for this rather than `vivado_hls`. Does this not work for you?

**Comment by definelicht** [comment]
This project can only be compiled for hardware execution with Vitis.

If you really want to, in principle you could run Vivado HLS on the kernel files independent of Vitis, which would give you the RTL output, although you wouldn't be able to run anything. For this you would have to make your own .tcl script and pass it to Vivado HLS with `vivado_hls -f my_tcl_script.tcl` (you can see the [template](https://github.com/spcl/gemm_hls/blob/master/scripts/Synthesis.tcl.in) that I use).

**Comment by prachikashikar** [comment]
@definelicht Thank you gain for replying so quickly. You saved a lot of my time with your concrete inputs. Let me try the way you explained. Thank you again for you kind replies.
