### ISSUE TITLE
undefined reference to cblas_sgemm

### ISSUE THREAD

**Issue by arrow53** [spcl/gemm_hls#22]
I see this during make
```
RunHardware.cpp:(.text+0x1504): undefined reference to `cblas_sgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, int, float const*, int, float, float*, int)'
```

from cmake I see these BLAS libraries included
```
/usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so
```

is this correct? Should I be seeing different libraries?

**Comment by arrow53** [comment]
this seemed to fix it `sudo apt-get install -y libopenblas-dev`

**Comment by definelicht** [comment]
It seems `find_package(BLAS)` is as bit too permissive so it passes if it finds Fortran librarieso nly, I'll take a look if there's a way to force it to find the C library.
