### ISSUE TITLE
Error when "make synthesis" ERROR: [HLS 207-2163] 'bitwidth' attribute requires integer constant between 1 and 4096 inclusive

### ISSUE THREAD

**Issue by Runbang** [spcl/gemm_hls#24]
When I run make synthesis. It gets errors
![0001dab6cf688535210992250d76416](https://user-images.githubusercontent.com/93361566/158084238-319132d7-b964-48ef-a8d6-aac93651b9d4.png)
 'bitwidth' attribute requires integer constant between 1 and 4096 inclusive. 
I changed all the size in Cmake but it's not working. My enviroment is Alveo U280, Vitis 2021.2.
Can you help me to solve the problem? Thanks.

**Comment by definelicht** [comment]
This was a bug with an update to `ConstLog2` in `hlslib` and has been fixed in master now. However, it seems like the project currently doesn't build with II=1 in the 2021.2, so I need to look into this.
