### ISSUE TITLE
How to use “v++ --config” to configure the kernel via cmake？

### ISSUE THREAD

**Issue by PDZZXL** [spcl/gemm_hls#30]
Hi, de fine licht
  It is indeed convenient to use cmake. However, I would like to use "v++ --config" to configure the kernels and allocate storage according to the xilinx tutorial on vitis. I tried to read the generated makefile, but it confused me. Can you provide some ideas, thanks!

![Untitled](https://user-images.githubusercontent.com/53367264/191663717-82d78c91-1d06-44e8-890d-0ac60f412e6a.png)
![Untitled2](https://user-images.githubusercontent.com/53367264/191663724-29e29f8b-90a3-4bef-a372-a109a02752eb.png)

**Comment by definelicht** [comment]
Hi there - what would you like to assign? There is the generic `MM_VITIS_FLAGS` option that you can use to pass anything you want to Vitis while configuring CMake.

**Comment by PDZZXL** [comment]
For example, if I want to instantiate MM on different SLRs, can I pass a profile through the MM_VITIS_FLAGS option to achieve this?

**Comment by definelicht** [comment]
Maybe this code can be an inspiration for you: https://github.com/spcl/apfp/blob/main/CMakeLists.txt#L44-L104
Either you can do something similar here (you would have to change the CMake), or you can use the commands from there in `MM_VITIS_FLAGS` directly.

**Comment by PDZZXL** [comment]
OK, I will try the above method and thank you for the information. Thanks!
